/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline": "#ac8884",
        "error-container": "#93000a",
        "surface-bright": "#3a3939",
        "on-primary-fixed-variant": "#93000b",
        "surface-container": "#201f1f",
        "primary": "#ffb4ab",
        "secondary-fixed-dim": "#eec200",
        "background": "#131313",
        "on-surface": "#e5e2e1",
        "on-secondary-fixed": "#231b00",
        "tertiary-fixed-dim": "#c6c6c7",
        "on-background": "#e5e2e1",
        "primary-container": "#dc2626",
        "on-tertiary-fixed": "#1a1c1c",
        "on-secondary-fixed-variant": "#574500",
        "tertiary-container": "#717272",
        "surface": "#131313",
        "on-tertiary": "#2f3131",
        "on-secondary-container": "#645000",
        "error": "#ffb4ab",
        "primary-fixed": "#ffdad6",
        "inverse-primary": "#bf0715",
        "tertiary": "#c6c6c7",
        "secondary": "#ffe083",
        "surface-variant": "#353534",
        "on-secondary": "#3c2f00",
        "surface-container-high": "#2a2a2a",
        "on-surface-variant": "#e6bdb8",
        "inverse-surface": "#e5e2e1",
        "on-primary": "#690005",
        "on-primary-fixed": "#410002",
        "tertiary-fixed": "#e2e2e2",
        "on-tertiary-container": "#f8f8f8",
        "on-error-container": "#ffdad6",
        "surface-dim": "#131313",
        "on-tertiary-fixed-variant": "#454747",
        "primary-fixed-dim": "#ffb4ab",
        "secondary-fixed": "#ffe083",
        "surface-container-highest": "#353534",
        "surface-container-lowest": "#0e0e0e",
        "secondary-container": "#eec200",
        "outline-variant": "#5c403c",
        "on-error": "#690005",
        "surface-tint": "#ffb4ab",
        "on-primary-container": "#fff6f5",
        "inverse-on-surface": "#313030",
        "surface-container-low": "#1c1b1b",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
      spacing: {
        "gutter": "24px",
        "container-max": "1280px",
        "margin-mobile": "20px",
        "unit": "8px",
        "section-gap": "120px",
        "margin-desktop": "64px",
      },
      fontFamily: {
        "display-lg": ["Anton"],
        "headline-lg": ["Anton"],
        "headline-md": ["Anton"],
        "headline-lg-mobile": ["Anton"],
        "body-md": ["Hanken Grotesk"],
        "label-md": ["JetBrains Mono"],
        "body-lg": ["Hanken Grotesk"],
      },
      fontSize: {
        "display-lg": ["80px", { lineHeight: "80px", letterSpacing: "0.02em", fontWeight: "400" }],
        "headline-lg": ["48px", { lineHeight: "52px", letterSpacing: "0.02em", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "28px", letterSpacing: "0.03em", fontWeight: "400" }],
        "headline-lg-mobile": ["32px", { lineHeight: "36px", letterSpacing: "0.02em", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

